name: Action - Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: #Manual execution will be good for debugging

jobs:
  get-module-to-validate:
    name: Get Changed Module
    uses: ./.github/workflows/detect-changes.yml

  validate-module-files:
    name: Validate Module
    runs-on: ubuntu-latest
    needs: get-module-to-validate
    if: needs.get-module-to-validate.outputs.module_dir
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # Adding a step to explicitly install the latest Bicep CLI because there is
      # always a delay in updating Bicep CLI in the job runner environments.
      - name: Install the latest Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --version

      - name: Install Bicep registry module tool
        run: dotnet tool install --global Azure.Bicep.RegistryModuleTool

      - name: Validate module files
        run: brm generate && brm validate
        working-directory: ${{ needs.get-module-to-validate.outputs.module_dir }}

      - name: PSRule for Azure - Well Architected
        uses: Microsoft/ps-rule@main
        continue-on-error: true # Setting until PSRule gets worked into the project.
        with:
          modules: "PSRule.Rules.Azure"
          inputPath: "${{ needs.get-module-to-validate.outputs.module_dir }}/test/parameters.json"

      - name: Git CheckIn
        uses: EndBug/add-and-commit@v7
        with:
          message: "Generated Files"
          add: "."

  validate-non-module-files:
    name: Validate Javascript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run prettier:check
